# NumPY 基础类型

In [2]:
import numpy as np
x = np.float32(1.0)
x

1.0

In [3]:
y = np.int_([1,2,4])
y

array([1, 2, 4])

In [5]:
z = np.arange(3, dtype=np.uint8)
z

array([0, 1, 2], dtype=uint8)

In [7]:
np.array([1,2,3], dtype='f')

array([1., 2., 3.], dtype=float32)

In [17]:
z.astype(float)

array([0., 1., 2.])

In [18]:
z.dtype

dtype('uint8')

In [19]:
np.int8(z)

array([0, 1, 2], dtype=int8)

In [20]:
z.dtype

dtype('uint8')

In [22]:
d = np.dtype(int)
d

dtype('int64')

In [23]:
np.issubdtype(d, np.integer)

True

In [24]:
np.issubdtype(d, np.floating)

False

In [25]:
# Overflow errors
np.power(100, 8, dtype=np.int64)

10000000000000000

In [26]:
np.power(100, 8, dtype=np.int32)

1874919424

In [27]:
np.iinfo(int)

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [28]:
np.iinfo(np.int32)

iinfo(min=-2147483648, max=2147483647, dtype=int32)

In [30]:
np.iinfo(np.int64)

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [31]:
np.power(100, 100, dtype=np.int64)

0

In [32]:
np.power(100, 100, dtype=np.float64)

1e+200