# Indexing

## Single element indexing

In [2]:
import numpy as np

x = np.arange(10)
x[2]

2

In [3]:
x[-2]

8

In [6]:
x.shape = (2, 5)
x[1, 3]

8

In [7]:
x[1, -1]

9

In [8]:
x[0][2]

2

## Other index options

In [13]:
x = np.arange(10)

In [14]:
x[2:5]

array([2, 3, 4])

In [15]:
x[:-7]

array([0, 1, 2])

In [20]:
x[1:7:2]

array([1, 3, 5])

In [29]:
y = np.arange(35).reshape(5, 7)
y[0:5:2, ::1]

array([[ 0,  1,  2,  3,  4,  5,  6],
       [14, 15, 16, 17, 18, 19, 20],
       [28, 29, 30, 31, 32, 33, 34]])

## Index arrays

In [32]:
x = np.arange(10, 1, -1)
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [35]:
x[np.array([3, 3, 1, 8])]

array([7, 7, 9, 2])

In [37]:
x[np.array([3,3,-3,8])]

array([7, 7, 4, 2])

In [38]:
x[np.array([3,3,20,8])]

IndexError: index 20 is out of bounds for axis 0 with size 9

In [39]:
x[np.array([[1,1],[2,3]])]

array([[9, 9],
       [8, 7]])

## Indexing Multi-dimensional arrays

In [45]:
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [46]:
y[np.array([0,2,4])]

array([[ 0,  1,  2,  3,  4,  5,  6],
       [14, 15, 16, 17, 18, 19, 20],
       [28, 29, 30, 31, 32, 33, 34]])

In [43]:
y[np.array([0,2,4]),np.array([0,1,2])]

array([ 0, 15, 30])

In [48]:
y[np.array([0,2,4]),0]

array([ 0, 14, 28])

In [49]:
y[np.array([0,2,4]),1]

array([ 1, 15, 29])

## Boolean or "mask" index arrays

In [54]:
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [55]:
b = y>20
y[b]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [56]:
b[:]

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [59]:
b[:,0]

array([False, False, False,  True,  True])

In [60]:
b[:,5]

array([False, False, False,  True,  True])

In [64]:
b[0:4,0]

array([False, False, False,  True])

In [65]:
b[1:3,0]

array([False, False])

In [53]:
y[b[:5]]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [66]:
x = np.arange(30).reshape(2,3,5)
x

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [70]:
b = np.array([[True, True, False], [False, True, True]])
b

array([[ True,  True, False],
       [False,  True,  True]])

In [71]:
x

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [69]:
x[b]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

## Combin index arrays with slices

In [73]:
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [72]:
y[np.array([0, 2, 4]), 1:3]

array([[ 1,  2],
       [15, 16],
       [29, 30]])

In [77]:
b = y > 20
b

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [78]:
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [76]:
y[b[:,5],1:3]

array([[22, 23],
       [29, 30]])

## Structural Indexing tools

In [80]:
y.shape

(5, 7)

In [81]:
y[:,np.newaxis,:].shape

(5, 1, 7)

In [84]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [85]:
x[:,np.newaxis] + x[np.newaxis,:]

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [90]:
z = np.arange(81).reshape(3,3,3,3)
z

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[54, 55, 56],
         [57, 58, 59],
         [60, 61, 62]],

        [[63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80]]]])

In [ ]:
z[1,...,2]

In [87]:
z[1,:,:,2]

array([[29, 32, 35],
       [38, 41, 44],
       [47, 50, 53]])

In [88]:
z[1]

array([[[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]],

       [[36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]],

       [[45, 46, 47],
        [48, 49, 50],
        [51, 52, 53]]])

## Assigning values to indexed arrays

In [93]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
x[2:7] = 1
x

array([0, 1, 1, 1, 1, 1, 1, 7, 8, 9])

In [97]:
x[1] = 1.2
x

array([0, 1, 1, 1, 1, 1, 1, 7, 8, 9])

In [98]:
x[1] = 1.2j
x

TypeError: can't convert complex to int

In [99]:
x = np.arange(0, 50, 10)
x

array([ 0, 10, 20, 30, 40])

In [101]:
x[np.array([1,1,3,1])] += 1
x

array([ 0, 11, 20, 31, 40])

## Dealing with variable numbers of indices within programs

In [103]:
z

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[54, 55, 56],
         [57, 58, 59],
         [60, 61, 62]],

        [[63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80]]]])

In [102]:
indices = (1,1,1,1)
z[indices]

40

In [104]:
indices = (1,1,1,slice(0,2))
z[indices]

array([39, 40])

In [105]:
indices = (1, Ellipsis, 1)
z[indices]

array([[28, 31, 34],
       [37, 40, 43],
       [46, 49, 52]])

In [106]:
z[[1,1,1,1]]

array([[[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]]])

In [107]:
z[(1,1,1,1)]

40